-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.chapter
(
    chap_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    novel_id integer,
    chap_write text COLLATE pg_catalog."default",
    chap_num integer,
    chap_create timestamp without time zone,
    CONSTRAINT chapter_pkey PRIMARY KEY (chap_id)
);

CREATE TABLE IF NOT EXISTS public.comment
(
    com_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_id integer,
    novel_id integer,
    com_text text COLLATE pg_catalog."default",
    CONSTRAINT comment_pkey PRIMARY KEY (com_id)
);

CREATE TABLE IF NOT EXISTS public.lastet_novel
(
    user_id integer,
    novel_id integer
);

CREATE TABLE IF NOT EXISTS public.novel
(
    novel_id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    novel_name character varying(255) COLLATE pg_catalog."default",
    novel_type_id integer,
    novel_img character varying COLLATE pg_catalog."default",
    novel_penname character varying(255) COLLATE pg_catalog."default",
    user_id integer,
    CONSTRAINT novel_pkey PRIMARY KEY (novel_id)
);

CREATE TABLE IF NOT EXISTS public.noveltype
(
    novel_type_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    novel_type_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT noveltype_pkey PRIMARY KEY (novel_type_id)
);

CREATE TABLE IF NOT EXISTS public.userinfo
(
    user_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    user_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_pass character varying(255) COLLATE pg_catalog."default" NOT NULL,
    user_email character varying(255) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT userinfo_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.chapter
    ADD CONSTRAINT chap_novel FOREIGN KEY (novel_id)
    REFERENCES public.novel (novel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT com_novel FOREIGN KEY (novel_id)
    REFERENCES public.novel (novel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.comment
    ADD CONSTRAINT com_user FOREIGN KEY (user_id)
    REFERENCES public.userinfo (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lastet_novel
    ADD CONSTRAINT lastet_novel FOREIGN KEY (novel_id)
    REFERENCES public.novel (novel_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.lastet_novel
    ADD CONSTRAINT lastet_user FOREIGN KEY (user_id)
    REFERENCES public.userinfo (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.novel
    ADD CONSTRAINT fk_novel_id FOREIGN KEY (user_id)
    REFERENCES public.userinfo (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL
    NOT VALID;


ALTER TABLE IF EXISTS public.novel
    ADD CONSTRAINT novel_noveltype FOREIGN KEY (novel_type_id)
    REFERENCES public.noveltype (novel_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;